include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_visible_for_testing_member: warning
    invalid_use_of_protected_member: warning
    unnecessary_cast: warning
    avoid_dynamic_calls: warning

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    directives_ordering: true
    sort_child_properties_last: true


